version: '3.3'
services:
   picframe:
     image: rcdemuth/pictureframe:latest
     ports:
      - "5000:5000"
     volumes:
       - PATH_TO_IMAGES:/app/static/images
       - PATH_TO_CONFIG:/app/config
     restart: always
