version: '3.3'
services:
   picframe:
     image: rcdemuth/pictureframe:latest
     ports:
      - "5000:5000"
     volumes:
       - /media/nas/evie_frame/pics:/app/static/images
       - /docker/eframe:/app/config
     restart: always
